apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-app-of-apps
  namespace: argo-cd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd 
  source:
    repoURL: "https://github.com/flphvlck/k8s-apps-labs.git"
    path: apps
    targetRevision: HEAD
  syncPolicy:
    automated: {}
    syncOptions:
      - ServerSideApply=true
