nameOverride: kps

alertmanager:
  enabled: false

kubeProxy:
  enabled: false

grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.lab.hvlck.xyz

prometheus-node-exporter:
  prometheus:
    monitor:
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: ^(.*)$
          targetLabel: instance
          replacement: $1
          action: replace

prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.lab.hvlck.xyz
  prometheusSpec:
    externalLabels:
      cluster: lab
      k8s_cluster: lab
    externalUrl: http://prometheus.lab.hvlck.xyz
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
