apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  source:
    repoURL: "https://kedacore.github.io/charts"
    chart: keda
    targetRevision: 2.16.1
#    helm:
#      valuesObject:
#        clusterName: lab
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
