apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argo-cd
#  finalizers:
#    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: "https://prometheus-community.github.io/helm-charts"
      chart: kube-prometheus-stack
      targetRevision: 68.4.4
      helm:
        releaseName: lab
        valueFiles:
          - $values/values/kube-prometheus-stack/values.yaml
    - repoURL: "https://github.com/flphvlck/k8s-apps-labs.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
