apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  sources:
    - repoURL: "https://kyverno.github.io/kyverno"
      chart: kyverno 
      targetRevision: 3.4.2
      helm:
        valueFiles:
          - $values/values/kyverno/values.yaml
    - repoURL: "https://github.com/flphvlck/k8s-apps-labs.git"
      targetRevision: HEAD
      ref: values
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
